####################################
# ELB     
####################################
variable "name" {
    description = "(Optional) The name of the ELB. By default generated by Terraform."
    type        = string
    default     = ""
}

variable "name_prefix" {
    description = "(Optional, Forces new resource) Creates a unique name beginning with the specified prefix. Conflicts with name."
    type        = string
    default     = null
}

variable "access_logs" {
    description = "(Optional) An Access Logs block. Access Logs documented below."
    type        = map(string)
    default     = null
}

variable "availability_zones" {
    description = "(Required for an EC2-classic ELB) The AZ's to serve traffic in."
    type        = list(string)
    default     = null
}

variable "security_groups" {
    description = "(Optional) A list of security group IDs to assign to the ELB. Only valid if creating an ELB within a VPC"
    type        = list(string)
    default     = null
}

variable "subnets" {
    description = "(Required for a VPC ELB) A list of subnet IDs to attach to the ELB."
    type        = list(string)
    default     = null
}

variable "instances" {
    description = "(Optional) A list of instance ids to place in the ELB pool."
    type        = list(string)
    default     = null
}

variable "internal" {
    description = "(Optional) If true, ELB will be an internal ELB."
    type        = bool
    default     = null
}

variable "cross_zone_load_balancing" {
    description = "(Optional) Enable cross-zone load balancing. Default: true"
    type        = bool
    default     = true
}

variable "idle_timeout" {
    description = "(Optional) The time in seconds that the connection is allowed to be idle. Default: 60"
    type        = number
    default     = 60
}

variable "connection_draining" {
    description = "(Optional) Boolean to enable connection draining. Default: false"
    type        = bool
    default     = false
}

variable "connection_draining_timeout" {
    description = "(Optional) The time in seconds to allow for connections to drain. Default: 300"
    type        = number
    default     = 300
}

variable "tags" {
    description = "(Optional) A map of tags to assign to the resource."
    type        = map(string)
}

variable "health_check" {
  description = "A health check block"
  type        = map(string)
  default     = null
}

variable "listener" {
  description = "A list of listener blocks"
  type        = list(map(string))
}
